### ISSUE TITLE
About trianing code and pretrianed model

### ISSUE THREAD

**Issue by yezhangyinge** [yxlu-0102/MS-BWE-demo#1]
Hello, I am interested in your great work! Would you consider open sourcing your training code and pretrained model? Thanks!

**Comment by yxlu-0102** [comment]
Hi, we will release the code in this [repository](https://github.com/yxlu-0102/AP-BWE) after the review of AP-BWE is completed.

**Comment by yezhangyinge** [comment]
Thanks for your reply! I will star that project and may I add you contact information? My wechat is yezhangyinge2. Thanks again.

**Comment by yxlu-0102** [comment]
Sure, I will contact you.

**Comment by yezhangyinge** [comment]
> Sure, I will contact you.

Thanks！
